### ISSUE TITLE
オプションを追加する

### ISSUE THREAD

**Issue by whywaita** [shokujinjp/data#2]
- 小辛 / 中辛 / 激辛
- 甘 / 激甘
- にんにく / 山椒 / たまご
- 具大盛り / ご飯大盛り / ハーフ

**Comment by alstamber** [comment]
* 山椒多め

**Comment by neotaso** [comment]
- 麺大盛り

**Comment by whywaita** [comment]
麺大盛りたしかに 👍 
麺メニュー追加すべきですね。

**Comment by whywaita** [comment]
ひとまずこのIssueでは「メニューに対して付与できるオプション」を考慮します。

方針としては、 `option_id` をユニークなIDとして持ち、メニューごとに注文可能なオプションをカラムの1つとして持とうかと思っています。
